//go:build linux

package main

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/ghostpsy/agent-linux/internal/privexec"
)

// agentUser is the locked system account the agent runs as. It cannot log in.
const agentUser = "ghostpsy"

func newSudoersCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "sudoers",
		Short: "Print the sudo rule the agent needs, and install nothing",
		Long: "Prints the exact list of commands ghostpsy may run as root on this server.\n" +
			"It changes nothing. Read it, then decide whether to install it.\n\n" +
			"The list is generated from this agent version and from what is actually\n" +
			"installed here, so it grants nothing for software you do not have.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			// A truncated grant file is worse than none: report a broken pipe
			// rather than let the caller install half a rule.
			_, err := fmt.Fprint(cmd.OutOrStdout(), sudoersFile())
			return err
		},
	}
}

func sudoersFile() string {
	header := "# /etc/sudoers.d/ghostpsy — generated by `ghostpsy sudoers`\n" +
		"#\n" +
		"# Every command ghostpsy may run as root on this server is listed below,\n" +
		"# and it may run nothing else. The agent refuses any command that is not\n" +
		"# here, before sudo is ever asked.\n" +
		"#\n" +
		"# Install with:  ghostpsy sudoers | sudo tee /etc/sudoers.d/ghostpsy\n" +
		"# Check it with: sudo visudo -c -f /etc/sudoers.d/ghostpsy\n" +
		"#\n" +
		"# After upgrading the agent, `ghostpsy sudoers --check` says whether this\n" +
		"# file still matches what it needs.\n\n"

	grant := privexec.Sudoers(agentUser)
	if grant == "" {
		return header + "# None of the software ghostpsy inspects with elevated rights is\n" +
			"# installed here, so nothing on this server needs a sudo rule.\n" +
			"# Install this file anyway if you like; it grants nothing.\n"
	}

	return header + grant
}
