//go:build linux

package firewall

import "testing"

// A real ufw-managed dump, trimmed. Taken from docker/debian-13.
const ufwSaveDump = `# Generated by iptables-save v1.8.11 (nf_tables) on Sat Aug 15 14:04:18 2026
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:ufw-before-input - [0:0]
:ufw-user-input - [0:0]
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -j ufw-before-output
-A ufw-user-input -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Sat Aug 15 14:04:18 2026
`

func TestParseIptablesSaveReadsDefaultPolicies(t *testing.T) {
	table := parseIptablesSave(ufwSaveDump)

	if got := table.Policies["INPUT"]; got != "DROP" {
		t.Errorf("INPUT policy: want DROP, got %q", got)
	}
	if got := table.Policies["OUTPUT"]; got != "ACCEPT" {
		t.Errorf("OUTPUT policy: want ACCEPT, got %q", got)
	}
}

// A user-defined chain has "-" where a built-in chain has its policy. Reporting
// "-" as a default policy would be wrong, so it must not be recorded as one.
func TestParseIptablesSaveIgnoresUserChainsWhenReadingPolicies(t *testing.T) {
	table := parseIptablesSave(ufwSaveDump)

	if _, found := table.Policies["ufw-before-input"]; found {
		t.Error("a user-defined chain must not be reported as having a default policy")
	}
}

func TestParseIptablesSaveCountsChainsAndRules(t *testing.T) {
	table := parseIptablesSave(ufwSaveDump)

	if len(table.Chains) != 5 {
		t.Errorf("chains: want 5, got %d (%v)", len(table.Chains), table.Chains)
	}
	if len(table.Rules) != 5 {
		t.Errorf("rules: want 5, got %d", len(table.Rules))
	}
}

func TestParseIptablesSaveFindsTheEstablishedRelatedRule(t *testing.T) {
	if !parseIptablesSave(ufwSaveDump).HasEstablishedRelated() {
		t.Error("expected the conntrack RELATED,ESTABLISHED rule to be found")
	}
}

func TestParseIptablesSaveDetectsUfwAsTheBackend(t *testing.T) {
	if !parseIptablesSave(ufwSaveDump).MentionsUfw() {
		t.Error("expected a ufw-managed table to be recognised")
	}
}

func TestParseIptablesSaveOnAPlainTableFindsNoUfwAndNoConntrack(t *testing.T) {
	plain := "*filter\n:INPUT ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n-A INPUT -p tcp --dport 80 -j ACCEPT\nCOMMIT\n"

	table := parseIptablesSave(plain)

	if table.MentionsUfw() {
		t.Error("a table with no ufw chains must not be reported as ufw-managed")
	}
	if table.HasEstablishedRelated() {
		t.Error("a table with no conntrack rule must not report one")
	}
	if got := table.Policies["INPUT"]; got != "ACCEPT" {
		t.Errorf("INPUT policy: want ACCEPT, got %q", got)
	}
}

// An empty dump means we could not read anything. It must not look like a
// server with no rules and an open policy — that is a different, alarming fact.
func TestParseIptablesSaveOnEmptyInputReportsNothing(t *testing.T) {
	table := parseIptablesSave("")

	if len(table.Policies) != 0 || len(table.Rules) != 0 || len(table.Chains) != 0 {
		t.Errorf("expected an empty dump to yield nothing, got %+v", table)
	}
}
