//go:build linux

package firewall

import "testing"

func TestRedactFirewallTelemetryLine(t *testing.T) {
	t.Parallel()
	if got := redactFirewallTelemetryLine("Status: active"); got != "Status: active" {
		t.Fatalf("got %q", got)
	}
	if got := redactFirewallTelemetryLine("  # Generated by UFW"); got != "#" {
		t.Fatalf("comment line: got %q", got)
	}
	if got := redactFirewallTelemetryLine("allow from 10.0.0.5 # office"); got != "allow from x.x.x.x" {
		t.Fatalf("ip + comment: got %q", got)
	}
	if got := redactFirewallTelemetryLine("2001:db8::1 in"); got != "x:x:x:x:x:x:x:x in" {
		t.Fatalf("v6: got %q", got)
	}
}

func TestRedactRulesetDumpForIngest(t *testing.T) {
	t.Parallel()
	in := "# Generated by iptables v1\n-A INPUT -s 203.0.113.7 -j DROP\n"
	got := redactRulesetDumpForIngest(in)
	if got != "#\n-A INPUT -s x.x.x.x -j DROP\n" {
		t.Fatalf("got %q", got)
	}
}
